### ISSUE TITLE
collaborate?

### ISSUE THREAD

**Issue by jonschlinkert** [terkelg/globalyzer#1]
Thanks for the attribution, it would have been awesome to have these ideas and improvements as contributions is-glob and glob-base. 

You write fantastic code, we have an org for globbing stuff so that the entire community can collaborate on making them better. I'd be happy to make you guys members and would love to have your involvement in improving those libs or whatever you're interested in. 

edit: I guess I'm also wondering why you are copying the code from those libs into this one, instead of requiring them in? Is it just to reduce a single dependency?

**Comment by terkelg** [comment]
Hi @jonschlinkert I'm totally up for that! Thanks for the kind words and all you amazing community work.

It's actually not for the dependencies but because I planned to do more customisation to them - especially look into performance (for tiny-glob). I also find it easier to work in one file than jumping around in different repos. I still plan to experiment and possible deviate further from the original code when I have time.

Let's work together!

**Comment by jonschlinkert** [comment]
Great! and thank you as well for the kind words!

> I also find it easier to work in one file than jumping around in different repos.

I agree. A few years ago, when I was learning to program I would create a module for whatever I was trying to learn. But lately I've been trying to reduce dependencies as much as possible.  [This is a good example](https://github.com/doowb/ansi-colors). 

I want to refactor our matching libs to reduce deps and improve performance. I'd love your help if you're interested. I don't have an emotional attachment to any libraries or approaches to doing anything. I just like writing code and collaborating on interesting projects.

**Comment by jonschlinkert** [comment]
btw, I created a library very similar to globrex about a year ago but never published it. It's a matching library like micromatch - not just for creating a regex, but it's minimal and has a kind-of-similar parsing approach. maybe I'll push that up for discussion.
